version: "3.6"
services:
    contactrabbitmq:
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password 
    
    contactapidb:
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=ContactDB
        
    reportapidb:
        ports: 
            - 5433:5432
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=ReportDB
        
    contactappgateway:
        ports:
            - 5000:80
            - 5001:443
                
    contactapi:
        ports:
            - 5002:80
            - 5003:443
        environment:
            - DefaultConnection=Server=contactapidb;Port=5432;User Id=admin;Password=admin;Database=ContactDB;SSL Mode=Disable;
        
    reportapi:
        ports:
            - 5004:80
            - 5005:443
        environment:
            - DefaultConnection=Server=reportapidb;Port=5432;User Id=admin;Password=admin;Database=ReportDB;SSL Mode=Disable;
            - RABBITMQ_HOSTNAME=contactrabbitmq
            - RABBITMQ_USERNAME=user
            - RABBITMQ_PASSWORD=password
            - RABBITMQ_REPORT_QUEUE=reportQueue
            - CONTACT_API=http://contactappgateway/contacts

    pgadmin:
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@admin.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - "5050:80"